#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Sixes

# Short bio or description (displayed in the header)
description: Sixes Dining, food with passion.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /build/img/Zenzez_Dining_logo_gold_green_pos_fc-800.png

#
# Flags below are optional
#

phone: +31 6 222 14 654

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: commerce.chaillet@gmail.com
  facebook: zenzezdining
  flickr:
  github: 1na/1na.github.io
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: zenzezdining
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  phone: +31 6 222222245


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: 
imgurl: /build/img/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# If you want the indexers to follow you define some value below (such as yes)
robots:

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v3.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
    - Gruntfile.js
    - renbserve.sh
